print("Operador de suma:")
print(4+3)
print("Operador de resta:")
print(4-3)
print("Operador de multiplicación:")
print(4*3)
print("Operador de división:")
print(4/3)
print("Operador de resto entero de división:")
print(4%3)
