print("Operador de menor que:")
print(4<3)
print("Operador de mayor que:")
print(4>3)
print("Operador de menor o igual que:")
print(4<=3)
print("Operador de mayor o igual que:")
print(4>=3)
print("Operador de igualdad:")
print(4==3)
print("Operador de no igualdad:")
print(4!=3)
