= RESTART: C:\Users\Alvaro\Documents\GitHub\python\001-Fundamentos de Python\005-Estructuras de control del flujo de la ejecución\001-Estructuras de bucle\001-for.py
hoy es el dia 1 del mes
hoy es el dia 2 del mes
hoy es el dia 3 del mes
hoy es el dia 4 del mes
hoy es el dia 5 del mes
hoy es el dia 6 del mes
hoy es el dia 7 del mes
hoy es el dia 8 del mes
hoy es el dia 9 del mes
hoy es el dia 10 del mes
hoy es el dia 11 del mes
hoy es el dia 12 del mes
hoy es el dia 13 del mes
hoy es el dia 14 del mes
hoy es el dia 15 del mes
hoy es el dia 16 del mes
hoy es el dia 17 del mes
hoy es el dia 18 del mes
hoy es el dia 19 del mes
hoy es el dia 20 del mes
hoy es el dia 21 del mes
hoy es el dia 22 del mes
hoy es el dia 23 del mes
hoy es el dia 24 del mes
hoy es el dia 25 del mes
hoy es el dia 26 del mes
hoy es el dia 27 del mes
hoy es el dia 28 del mes
hoy es el dia 29 del mes
hoy es el dia 30 del mes
y esto está ya fuera del bucle